config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'charges/create'

  get 'user/index'

  get 'user/show'

  resources :charges, only: [:new, :create]

  resources :wikis
  
  get 'about' => 'welcome#about'

 root to: 'welcome#index'
end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base
  belongs_to :wiki
  belongs_to :user
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :wikis
  
  
  def standard?
    role == 'standard'
  end

  def admin?
    role == 'admin'
  end

  def premium?
    role == 'premium'
  end
  
  def downgrade_wikis
    Wiki.where(user: self, public: false).each do |wiki|
      wiki.update_attributes(public: true)
    end
  end
  
  
  
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user
  
  scope :visible_to, -> (user) { user ? all : where(private: false)}
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  include Pundit
  
  rescue_from Pundit::NotAuthorizedError do |exception|
     redirect_to root_url, alert: exception.message
   end

  protect_from_forgery with: :exception
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  
  
  
  
 before_filter :authenticate_user!
  
 def new
   @amount = 15_00
   @stripe_btn_data = {
    key: "#{ Rails.configuration.stripe[:publishable_key] }",
    description: "Premium Membership - #{current_user.name}",
    amount: @amount
   }
 end
  
 def create
  @amount = 15_00
  # Creates a Stripe Customer object, for associating
  # with the charge
  customer = Stripe::Customer.create(
    email: current_user.email,
    card: params[:stripeToken]
  )
 
  # Where the real magic happens   
  charge = Stripe::Charge.create(
    customer: customer.id, # Note -- this is NOT the user_id in your app
    amount: @amount,
    description: "Premium Membership - #{current_user.email}",
    currency: 'usd'
  )
   
   current_user.update_attributes!( role: 'premium' )
   
  flash[:success] = "Thanks for all the money, #{current_user.email}! Feel free to pay me again."
  redirect_to wikis_path # or wherever
 
 # Stripe will send back CardErrors, with friendly messages
 # when something goes wrong.
 # This `rescue block` catches and displays those errors.
 rescue Stripe::CardError => e
   flash[:error] = e.message
   redirect_to new_charge_path
 end
 
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  def index
    @wikis = policy_scope(Wiki)
    authorize @wikis
  end

  def show
    @wiki = Wiki.find(params[:id])
  end

  def new
    @wiki = Wiki.new
    authorize @wiki
  end
  
  
  def create
     @wiki = Wiki.new(params.require(:wiki).permit(:title, :body))
     #raise # this will short-circuit the method
     authorize @wiki
     if @wiki.save
       flash[:notice] = "Wiki was saved."
       redirect_to @wiki
     else
       flash[:error] = "There was an error saving the wiki. Please try again."
       render :new
     end
  end

  def edit
    @wiki = Wiki.find(params[:id])
    authorize @wiki
  end
  
  def update
     @wiki = Wiki.find(params[:id])
     authorize @wiki
     if @wiki.update_attributes(params.require(:wiki).permit(:title, :body))
       flash[:notice] = "Wiki was updated."
       redirect_to @wiki
     else
       flash[:error] = "There was an error saving the wiki. Please try again."
       render :edit
     end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
    


def markdown_to_html(markdown)
  renderer = Redcarpet::Render::HTML.new
  extensions = {fenced_code_blocks: true}
  redcarpet = Redcarpet::Markdown.new(renderer, extensions)
  (redcarpet.render markdown).html_safe
end
    
    
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>$15.00</strong>!</h2>

app/views/charges/new.html.erb
<div class="row">
  <div class="col-md-8">
    <h1>Premium Account</h1>
    <li>As a premium member, you will have access to create an unlimited amount of private wikis. Additionally, for each private wiki you may choose a selection of collaborators from our user list. </li>
    </br>


<%= form_tag charges_path do %>
   <h4>Upgrade Today for $15!</h4>
   <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount="<%= @stripe_btn_data[:amount] %>" data-description="<%= @stripe_btn_data[:description] %>" ></script>
<% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>blocipedia</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class='container custom-nav-styles'>
      <div class='inner-wrapper'>
         <ul class='nav nav-tabs'>
          <li class='blocipedia-logo' ><%= link_to 'Blocipedia', root_url %></li>
          <li><%= link_to 'Wikis', wikis_path %> </li>
          <li><%= link_to 'New Wiki', new_wiki_path %> </li>
          <div class='user-info pull-right'>
            <% if current_user %>
              Hello!
              <%= link_to current_user.email, edit_user_registration_path %>
              <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
            <% else %>
              <%= link_to 'Log In', new_user_session_path %> or
              <%= link_to 'Join Us', new_user_registration_path %>
            <% end %>
          </div>
        </ul>
      </div>
    </div>
    <% if flash[:notice] %>
        <div class='alert alert-success'>
          <button type='button' class='close' data-dismiss='alert'>&times;</button>
          <%= flash[:notice] %>
        </div>
      <% elsif flash[:error] %>
        <div class='alert alert-danger'>
          <button type='button' class='close' data-dismiss='alert'>&times;</button>
          <%= flash[:error] %>
        </div>
      <% elsif flash[:alert] %>
        <div class='alert alert-warning'>
          <button type='button' class='close' data-dismiss='alert'>&times;</button>
          <%= flash[:alert] %>
        </div>
      <% end %>
    <%= yield %>
    <div class='container footer'>
      <div class='inner-wrapper'>
        <footer>Created by Kidus Yohans</footer>
      </div>
    </div>
  </body>
</html>

app/views/user/index.html.erb
<h1>User#index</h1>
<p>Find me in app/views/user/index.html.erb</p>

app/views/user/show.html.erb
<h1>User#show</h1>
<p>Find me in app/views/user/show.html.erb</p>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<div class="jumbotron">
	<h1 align="center">Blocipedia</h1>
	<p class="lead" align="center">Your wiki.</p>
</div>
<div class="container">
	<div class="text-center">
		<h2>Create and Edit Wikis Now</h2>
		<h2>Sign Up For An Account Today</h2>
		<%= link_to "Sign Up", new_user_registration_path, :class => "btn btn-lg btn-primary", :method => :get %>
	</br>
		<%= link_to "Log In", new_user_session_path, :class => "btn btn-lg btn-primary", :method => :get %>
	</div>
</div>

app/views/wikis/_form.html.erb
<% if current_user.role == 'admin' || current_user.role == 'premium' %>
    <div class="form-group">
      <%= f.label :private, class: 'checkbox' do %>
      <%= f.check_box :private %> Private wiki
    <% end %>
  </div>
<% end %>

app/views/wikis/edit.html.erb
<div class='container filler-height'>
  <div class='inner-wrapper'>
    <h1>Edit your Wiki</h1>
    <%= form_for @wiki do |f| %>
    <div class='form-group'>
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control'%>
    </div>
    <div class='form-group'>
      <%= f.label :body %>
      <%= f.text_area :body, rows: 12,  class: 'form-control'%>
    </div>
    <div class="form-group">
         <%= f.submit "Save", class: 'btn btn-success' %>
       </div>
     <% end %>
   </div>
 </div>

app/views/wikis/index.html.erb
<h1>All Wikis</h1>

<% if policy(Wiki.new).create? %>
<%= link_to "New Wiki", new_wiki_path, class: 'btn btn-success' %>
<% end %>
<% @wikis.each do | wiki | %>
  <div class="media">
     <div class="media-body">
       <h4 class="media-heading">
         <%= link_to wiki.title, wiki %>
       </h4>
     </div>
   </div>
<% end %>

app/views/wikis/new.html.erb
<div class='container filler-height'>
  <div class='inner-wrapper'>
    <h1>New Wiki</h1>
    <%= form_for @wiki do |f| %>
      <div class='form-group'>
        <%= f.label :title %>
        <%= f.text_field :title,  class: 'form-control', placeholder: 'Enter Wiki title.'%>
      </div>
      <div class='form-group'>
        <%= f.label :body %>
        <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: 'Enter Wiki body'%>
      </div>
       <div class="form-group">
         <%= f.submit "Save", class: 'btn btn-success' %>
       </div>
     <% end %>
   </div>
 </div>

app/views/wikis/show.html.erb
<h1><%= markdown_to_html @wiki.title %></h1>

<% if policy(@wiki).edit? %>
<%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn-success' %>
<% end %>

<p><%= markdown_to_html @wiki.body %></p>